### ISSUE TITLE
EEGModule can not reject channels

### ISSUE THREAD

**Issue by ishiikurisu** [ishiikurisu/P2#8]
There's a commented line (bad programming habits there tsc tsc) that indicates EEGModule would be able to reject some channels, but the script does not work when this line is uncommented. Why??

**Comment by ishiikurisu** [comment]
After updating the code concerns about the data set, the channel rejection is now running smoothly. Early tests show they are indeed being removed from the data set. The problem might have dwelled on the way we were dealing the datasets.

**Comment by crs94** [comment]
It still doesn't work on the computer I use to code.

**Comment by crs94** [comment]
Changing the order of the process seems to work well.

**Comment by ishiikurisu** [comment]
Can EEGModule reject more than one channel?
